// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqaongggjcfuhaupygjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxYW9uZ2dnamNmdWhhdXB5Z2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MjQxMjksImV4cCI6MjA1NTMwMDEyOX0.sVqh4pcADnGgk7PutZlNO330RObn6_XAqXG6s-wtTdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);